version: '2.2'

services:
  qdrant:
    image: qdrant/qdrant
    restart: always
    ports:
      - '6333:6333'
    volumes:
      - ./data:/qdrant/storage

  chatbot:
    build: ./chatbot
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: always
    environment:
      FLASK_PORT: 5000
    depends_on:
      - qdrant


