# Используем базовый образ Python
FROM python:3.10

# Установим рабочую директорию внутри контейнера
WORKDIR /app

RUN apt-get update && apt-get install -y \
    libsndfile1  ffmpeg\
    && rm -rf /var/lib/apt/lists/*

# Скопируем файлы приложения в контейнер
COPY ./requirements.txt ./
COPY ./templates/ ./templates/
RUN pip install --no-cache-dir -r requirements.txt


COPY ./app.py ./

# Запускаем приложение
CMD ["python", "app.py"]
